MCU = STM32G474

BOOTLOADER = stm32-dfu
BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SLEEP_LED_ENABLE = no
NKRO_ENABLE = yes # requires FORCE_NRKO define or keybind!
UNICODE_ENABLE = no
WPM_ENABLE = no

SPLIT_KEYBOARD = yes
SERIAL_DRIVER = fdcan

ENCODER_ENABLE = no

USBPD_ENABLE = yes

WS2812_DRIVER = pwm
CIE1931_CURVE = yes

RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812

EEPROM_DRIVER = spi

AUDIO_ENABLE = no

LTO_ENABLE = yes
OPT = 2
